### ISSUE TITLE
Add example to homepage

### ISSUE THREAD

**Issue by paulathevalley** [FormidableLabs/formidable-charts-docs#20]
/cc @ebrillhart @kenwheeler Thoughts on which gif to feature? Alternatively, would a playground be better? 

See https://github.com/FormidableLabs/formidable-charts/blob/master/docs/themes.md

**Comment by ebrillhart** [comment]
@paulathevalley the issue with the existing gifs is that they still have the "victory" titled components, so that would need to be changed. I think a playground could be cool, especially after Imran's comments about missing the editable examples in the victory docs today.

**Comment by paulathevalley** [comment]
Playground added!
